---

  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

