---
version: "3"
services:
  discord-fury:
    build: .
    volumes:
      - "./data:/app/data:rw"
    environment:
      - UID=1000 
      - GID=1000
    stdin_open: true
    tty: true
    restart: unless-stopped
